environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc

branches:
  only:
  - develop
  - master

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V
  - echo [workspace] > Cargo.toml
  - echo members = [ >> Cargo.toml
  - echo "snips-nlu-ffi", >> Cargo.toml
  - echo "snips-nlu-ffi/python/snips-nlu-python-ffi", >> Cargo.toml
  - echo "snips-nlu-lib", >> Cargo.toml
  - echo ] >> Cargo.toml
  - ps: (Get-Content snips-nlu-ffi/python/snips-nlu-python-ffi/Cargo.toml) | ForEach-Object { $_ -replace "^snips-nlu-ffi = .*$", "snips-nlu-ffi = { path = `"../..`" }" } | Set-Content snips-nlu-ffi/python/snips-nlu-python-ffi/Cargo.toml

build: false

test_script:
  - cargo build --all --tests --benches
  - cargo test --all
