cache:
- cargo
- directories:
  - platforms/python/ffi/target

jobs:
  include:
    - if: branch = master or head_branch =~ /^release\/.+$/
      os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - if: branch = master or head_branch =~ /^release\/.+$/
      os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: branch = master or head_branch =~ /^release\/.+$/
      os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - MACOS_SWIFT_TESTS=true
        - IOS_SWIFT_TESTS=true
    - if: branch = master or head_branch =~ /^release\/.+$/
      os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: branch = master or head_branch =~ /^release\/.+$/
      os: linux
      language: rust
      rust: stable
      env:
        - KOTLIN_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true

before_install: . ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/test.sh

git:
  depth: 10
