jobs:
  include:
    - if: head_branch =~ /^release\/.+$/ or head_branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode10.2
      language: generic
      sudo: true
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - if: head_branch =~ /^release\/.+$/ or head_branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode10.2
      language: generic
      sudo: true
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: head_branch =~ /^release\/.+$/ or head_branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode10.2
      language: generic
      sudo: true
      env:
        - MACOS_SWIFT_TESTS=true
        - IOS_SWIFT_TESTS=true
    - if: head_branch =~ /^release\/.+$/ or head_branch =~ /^main\/.+$/
      os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: head_branch =~ /^release\/.+$/ or head_branch =~ /^main\/.+$/
      os: linux
      language: java
      jdk: openjdk8
      env:
        - KOTLIN_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true

before_install: . ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/test.sh
